// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Roles {
boolean: boolean
roleContext: RoleContext
roleEditorData: RoleEditorData
[k: string]: unknown
}
export interface RoleContext {
  app: string;
  file: string;
  pmv: string;
}
export interface RoleEditorData {
  context: RoleContext;
  data: RoleData[];
}
export interface RoleData {
  displayName: string;
  id: string;
  members: string[];
  parent: string;
}
