// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = ("INFO" | "WARNING" | "ERROR")

export interface Roles {
  boolean: boolean;
  editorFileContent: EditorFileContent;
  roleContext: RoleContext;
  roleEditorData: RoleEditorData;
  roleSaveDataArgs: RoleSaveDataArgs;
  validationResult: ValidationResult[];
  [k: string]: unknown;
}
export interface EditorFileContent {
  content: string;
}
export interface RoleContext {
  app: string;
  file: string;
  pmv: string;
}
export interface RoleEditorData {
  context: RoleContext;
  data: RoleData[];
  helpUrl: string;
  readonly: boolean;
}
export interface RoleData {
  displayName: string;
  id: string;
  members: string[];
  parent: string;
}
export interface RoleSaveDataArgs {
  context: RoleContext;
  data: RoleData[];
  directSave: boolean;
}
export interface ValidationResult {
  message: string;
  path: string;
  severity: Severity;
}
